# Generated by Django 4.1.2 on 2022-10-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='reg_no',
            field=models.CharField(default=3, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
