# Generated by Django 4.1.2 on 2022-10-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_voter_reg_no_alter_voter_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='reg_no',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
