# Generated by Django 4.1.2 on 2022-10-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_voter_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='reg_no',
            field=models.CharField(default=4, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
